---
# tasks file for van4sh.environment

- name: Ensure home directory exists
  file:
    path: "/home/{{ username }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Create .bashrc with alias
  copy:
    content: 'alias ll="ls -la"\n'
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Create .gitconfig with user details
  copy:
    content: |
      [user]
          name = {{ username }}
          email = {{ email }}
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add SSH public key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
