- hosts: webservers
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      loop:
        - { name: jaime }
        - { name: sansa }
        - { name: robert }

    - name: Create .ssh directory 
      ansible.builtin.file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        mode: '0700'
      loop:
        - { name: jaime }
        - { name: sansa }
        - { name: robert }

    - name: Update gitconfig
      ansible.builtin.copy:
        src: /home/ivan/ansible_learn/gitconfig.conf.j2
        dest: "/home/{{ item.name }}/.gitconfig"
      loop:
        - { name: jaime }
        - { name: sansa }
        - { name: robert }

    - name: Upload SSH key
      ansible.builtin.copy:
        src: /home/ivan/ansible_learn/ssh.txt
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        mode: '0600'
      loop:
        - { name: jaime }
        - { name: sansa }
        - { name: robert }




